pub const DAY_IN_LEDGERS: u32 = 17280;
pub const ADAPTER_INSTANCE_BUMP_AMOUNT: u32 = 7 * DAY_IN_LEDGERS;
pub const ADAPTER_INSTANCE_LIFETIME_THRESHOLD: u32 = ADAPTER_INSTANCE_BUMP_AMOUNT - DAY_IN_LEDGERS;
